<a href="https://colab.research.google.com/github/Gabriela-Reiss/Algoritmo_Verifica-o_Decolagem/blob/main/Script_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SCRIPT EM PYTHON - ANÁLISE DE PRÉ-DECOLAGEM**

**DADOS USADOS PARA A CONSTRUÇÃO DO SCRIPT:**

Os dados para a construção do script em python foram gerados pelo Gemini em um arquivo de extensão CSV, nomeado: "dataset_telemetria.csv".

Para a execução do script, anexe diretamente o arquivo do dataset na aba "Arquivos" do Notebook ou use o prompt já criado (disponível no documento PDF da atividade) para que o dataset seja criado pela IA

**Carregamento do dataset gerado:**

In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv("dataset_telemetria.csv")

In [3]:
dados.head(10)

,timestamp,temperatura_interna_c,temperatura_externa_c,integridade_estrutural,energia_maxima_kwh,energia_disponivel_kwh,pressao_tanque_bar,status_modulos_criticos
0,2026-09-08 12:00:00,30.52,18.68,1,775.80,367.68,116.10,1
1,2026-09-08 12:15:00,18.45,1.96,1,1029.98,697.80,106.02,1
2,2026-09-08 12:30:00,28.02,23.33,1,901.30,784.54,129.91,1
3,2026-09-08 12:45:00,23.78,0.44,1,1091.44,566.39,210.85,1
4,2026-09-08 13:00:00,28.26,23.25,1,794.30,700.00,75.42,1
5,2026-09-08 13:15:00,24.15,1.73,1,913.91,705.96,133.65,1
6,2026-09-08 13:30:00,34.75,24.94,1,1073.30,593.95,117.67,1
7,2026-09-08 13:45:00,32.18,0.69,1,971.05,133.53,130.09,1
8,2026-09-08 14:00:00,22.16,11.18,1,953.99,905.20,210.57,1
9,2026-09-08 14:15:00,31.19,3.02,1,906.42,491.30,108.39,1

In [4]:
dados.tail()

,timestamp,temperatura_interna_c,temperatura_externa_c,integridade_estrutural,energia_maxima_kwh,energia_disponivel_kwh,pressao_tanque_bar,status_modulos_criticos
25,2026-09-08 18:15:00,28.00,3.05,1,944.04,345.72,126.56,1
26,2026-09-08 18:30:00,21.89,26.69,1,1071.93,354.70,106.90,1
27,2026-09-08 18:45:00,29.37,2.50,1,926.46,886.06,123.55,1
28,2026-09-08 19:00:00,26.04,22.46,1,1061.50,445.00,99.85,1
29,2026-09-08 19:15:00,25.33,9.83,1,993.40,805.54,128.67,1

In [5]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   timestamp                30 non-null     object
 1   temperatura_interna_c    30 non-null     float64
 2   temperatura_externa_c    30 non-null     float64
 3   integridade_estrutural   30 non-null     int64
 4   energia_maxima_kwh       30 non-null     float64
 5   energia_disponivel_kwh   30 non-null     float64
 6   pressao_tanque_bar       30 non-null     float64
 7   status_modulos_criticos  30 non-null     int64
dtypes: float64(5), int64(2), object(1)
memory usage: 2.0+ KB

**Criação de Algoritmo de Classificação dos dados e análise de status para decolagem**

In [6]:
resultados = []

for indice, linha in dados.iterrows():

    temperatura_interna = linha["temperatura_interna_c"]
    temperatura_externa = linha["temperatura_externa_c"]
    integridade_estrutural = linha["integridade_estrutural"]

    energia_maxima = linha["energia_maxima_kwh"]
    energia_disponivel = linha["energia_disponivel_kwh"]

    pressao_tanque = linha["pressao_tanque_bar"]
    status_modulos = linha["status_modulos_criticos"]

    # Cálculo do nível de energia
    nivel_energia = (
        energia_disponivel / energia_maxima
    ) * 100


# definição das condições referente aos valores permitidos em cada variável e mensagem de motivos, caso condição seja falsa
    regras = [
        (
            18 <= temperatura_interna <= 35,
            "temperatura interna fora do limite"
        ),
        (
            -5 <= temperatura_externa <= 30,
            "temperatura externa fora do limite"
        ),
        (
            integridade_estrutural == 1,
            "integridade estrutural comprometida"
        ),
        (
            energia_disponivel <= energia_maxima,
            "energia disponível superior à capacidade máxima"
        ),
        (
            nivel_energia >= 60,
            "nível de energia abaixo de 60%"
        ),
        (
            95 <= pressao_tanque <= 145,
            "pressão do tanque fora do limite"
        ),
        (
            status_modulos == 1,
            "módulo crítico com falha"
        )
    ]



# armazenamento das mensagens na lista de motivos, para uma justificativa de cada decisão da verificação
    motivos = [
        mensagem
        for condicao, mensagem in regras
        if not condicao
    ]


# definição da decisão com base na presença de motivos armazenados (caso tenha motivos = decolagem abortada - estava fora dos limites permitidos)
    decisao = (
        "PRONTO PARA DECOLAR\n"
        if not motivos
        else "DECOLAGEM ABORTADA"
    )

    print(indice,
        linha["timestamp"],
        "-",
        decisao
    )

    if motivos:
        print("  Motivo(s):", "; ".join(motivos), "\n")


# salvando dados de telemetria e decisões em um data frame
    resultados.append({
    "timestamp": linha["timestamp"],
    "temperatura_interna": temperatura_interna,
    "temperatura_externa": temperatura_externa,
    "integridade_estrutural": integridade_estrutural,
    "nivel_energia": nivel_energia,
    "pressao_tanque": pressao_tanque,
    "status_modulos_criticos": status_modulos,
    "decisao": decisao,
    "motivos": "; ".join(motivos) if motivos else "Nenhum"
})

0 2026-09-08 12:00:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

1 2026-09-08 12:15:00 - PRONTO PARA DECOLAR

2 2026-09-08 12:30:00 - PRONTO PARA DECOLAR

3 2026-09-08 12:45:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%; pressão do tanque fora do limite

4 2026-09-08 13:00:00 - DECOLAGEM ABORTADA
  Motivo(s): pressão do tanque fora do limite

5 2026-09-08 13:15:00 - PRONTO PARA DECOLAR

6 2026-09-08 13:30:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

7 2026-09-08 13:45:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

8 2026-09-08 14:00:00 - DECOLAGEM ABORTADA
  Motivo(s): pressão do tanque fora do limite

9 2026-09-08 14:15:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

10 2026-09-08 14:30:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

11 2026-09-08 14:45:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

12 2026-09-08 15:00:00 - PRONTO PARA DECOLAR

13 2026-09-08 15:15:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

14 2026-09-08 15:30:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

15 2026-09-08 15:45:00 - PRONTO PARA DECOLAR

16 2026-09-08 16:00:00 - PRONTO PARA DECOLAR

17 2026-09-08 16:15:00 - PRONTO PARA DECOLAR

18 2026-09-08 16:30:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

19 2026-09-08 16:45:00 - PRONTO PARA DECOLAR

20 2026-09-08 17:00:00 - DECOLAGEM ABORTADA
  Motivo(s): temperatura interna fora do limite; módulo crítico com falha

21 2026-09-08 17:15:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

22 2026-09-08 17:30:00 - PRONTO PARA DECOLAR

23 2026-09-08 17:45:00 - DECOLAGEM ABORTADA
  Motivo(s): energia disponível superior à capacidade máxima; pressão do tanque fora do limite

24 2026-09-08 18:00:00 - DECOLAGEM ABORTADA
  Motivo(s): módulo crítico com falha

25 2026-09-08 18:15:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

26 2026-09-08 18:30:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

27 2026-09-08 18:45:00 - PRONTO PARA DECOLAR

28 2026-09-08 19:00:00 - DECOLAGEM ABORTADA
  Motivo(s): nível de energia abaixo de 60%

29 2026-09-08 19:15:00 - PRONTO PARA DECOLAR

**Salvando o dataset completo e os resultados em um novo Data Frame**

In [7]:
resultados_df = pd.DataFrame(resultados)

print(resultados_df)

              timestamp  temperatura_interna  temperatura_externa  \
0   2026-09-08 12:00:00                30.52                18.68
1   2026-09-08 12:15:00                18.45                 1.96
2   2026-09-08 12:30:00                28.02                23.33
3   2026-09-08 12:45:00                23.78                 0.44
4   2026-09-08 13:00:00                28.26                23.25
5   2026-09-08 13:15:00                24.15                 1.73
6   2026-09-08 13:30:00                34.75                24.94
7   2026-09-08 13:45:00                32.18                 0.69
8   2026-09-08 14:00:00                22.16                11.18
9   2026-09-08 14:15:00                31.19                 3.02
10  2026-09-08 14:30:00                21.59                28.00
11  2026-09-08 14:45:00                24.73                27.01
12  2026-09-08 15:00:00                27.54                 4.20
13  2026-09-08 15:15:00                21.73                29.91
14  2026-09-08 15:30:00                19.86                16.96
15  2026-09-08 15:45:00                24.49                29.86
16  2026-09-08 16:00:00                18.20                20.23
17  2026-09-08 16:15:00                28.90                -1.10
18  2026-09-08 16:30:00                32.89                 4.22
19  2026-09-08 16:45:00                32.80                 5.45
20  2026-09-08 17:00:00                47.80                13.88
21  2026-09-08 17:15:00                24.17                29.49
22  2026-09-08 17:30:00                27.65                -2.24
23  2026-09-08 17:45:00                27.06                -0.60
24  2026-09-08 18:00:00                30.12                 8.96
25  2026-09-08 18:15:00                28.00                 3.05
26  2026-09-08 18:30:00                21.89                26.69
27  2026-09-08 18:45:00                29.37                 2.50
28  2026-09-08 19:00:00                26.04                22.46
29  2026-09-08 19:15:00                25.33                 9.83

    integridade_estrutural  nivel_energia  pressao_tanque  \
0                        1      47.393658          116.10
1                        1      67.748888          106.02
2                        1      87.045379          129.91
3                        1      51.893828          210.85
4                        1      88.127911           75.42
5                        1      77.246118          133.65
6                        1      55.338675          117.67
7                        1      13.751094          130.09
8                        1      94.885691          210.57
9                        1      54.202246          108.39
10                       1      50.588224          127.77
11                       1      48.725007          107.33
12                       1      92.796877          114.97
13                       1      36.311645           97.36
14                       1      58.593942           98.18
15                       1      97.970810          138.04
16                       1      67.100565          108.34
17                       1      61.977810          142.69
18                       1      42.502900          140.63
19                       1      72.310491          102.64
20                       1      66.380609           95.03
21                       1      45.443068          107.04
22                       1      86.876660          143.90
23                       1     125.104898           67.59
24                       1      76.490256          139.98
25                       1      36.621330          126.56
26                       1      33.089847          106.90
27                       1      95.639315          123.55
28                       1      41.921809           99.85
29                       1      81.089189          128.67

    status_modulos_criticos                decisao  \
0                         1     DECOLAGEM ABORTADA
1                         1  PRONTO PARA DECOLAR\n
2                         1  PRONTO PARA DECOLAR\n
3                         1     DECOLAGEM ABORTADA
4                         1     DECOLAGEM ABORTADA
5                         1  PRONTO PARA DECOLAR\n
6                         1     DECOLAGEM ABORTADA
7                         1     DECOLAGEM ABORTADA
8                         1     DECOLAGEM ABORTADA
9                         1     DECOLAGEM ABORTADA
10                        1     DECOLAGEM ABORTADA
11                        1     DECOLAGEM ABORTADA
12                        1  PRONTO PARA DECOLAR\n
13                        1     DECOLAGEM ABORTADA
14                        1     DECOLAGEM ABORTADA
15                        1  PRONTO PARA DECOLAR\n
16                        1  PRONTO PARA DECOLAR\n
17                        1  PRONTO PARA DECOLAR\n
18                        1     DECOLAGEM ABORTADA
19                        1  PRONTO PARA DECOLAR\n
20                        0     DECOLAGEM ABORTADA
21                        1     DECOLAGEM ABORTADA
22                        1  PRONTO PARA DECOLAR\n
23                        1     DECOLAGEM ABORTADA
24                        0     DECOLAGEM ABORTADA
25                        1     DECOLAGEM ABORTADA
26                        1     DECOLAGEM ABORTADA
27                        1  PRONTO PARA DECOLAR\n
28                        1     DECOLAGEM ABORTADA
29                        1  PRONTO PARA DECOLAR\n

                                              motivos
0                      nível de energia abaixo de 60%
1                                              Nenhum
2                                              Nenhum
3   nível de energia abaixo de 60%; pressão do tan...
4                    pressão do tanque fora do limite
5                                              Nenhum
6                      nível de energia abaixo de 60%
7                      nível de energia abaixo de 60%
8                    pressão do tanque fora do limite
9                      nível de energia abaixo de 60%
10                     nível de energia abaixo de 60%
11                     nível de energia abaixo de 60%
12                                             Nenhum
13                     nível de energia abaixo de 60%
14                     nível de energia abaixo de 60%
15                                             Nenhum
16                                             Nenhum
17                                             Nenhum
18                     nível de energia abaixo de 60%
19                                             Nenhum
20  temperatura interna fora do limite; módulo crí...
21                     nível de energia abaixo de 60%
22                                             Nenhum
23  energia disponível superior à capacidade máxim...
24                           módulo crítico com falha
25                     nível de energia abaixo de 60%
26                     nível de energia abaixo de 60%
27                                             Nenhum
28                     nível de energia abaixo de 60%
29                                             Nenhum

**Convertendo o Data Frame em JSON para análise da IA**

In [8]:
dados_para_ia = resultados_df.to_json(
    orient="records",
    force_ascii=False
)

## **ANÁLISE ASSISTIDA POR IA**

Visando obter uma análise detalhada dos resultados e dados por IA, utilizamos uma integração com a API Gemini (modelo Gemini 3.6 Flash)

O objetivo dessa integração é permitir que a IA dê sugestões de melhorias e analise os resultados do algoritmo.

In [9]:
import os
from google.colab import userdata

**Para conseguir executar, gere uma API Key no Google IA Studio (https://aistudio.google.com/api-keys) e configure-a na aba "Secrets" do Notebook**

In [10]:
os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

In [11]:
from google import genai

client = genai.Client()
chat = client.chats.create(model="gemini-3.6-flash")

**Prompt descrevendo as informações que devem ser analisadas pela IA**

In [14]:
# prompt para IA com as informações que desejamos que ela analise e gere uma resposta pertinente
resposta = chat.send_message(f"""Quero que você atue como um sistema de apoio à análise operacional de pré-decolagem
de uma nave espacial.

Preciso que você analise os dados fornecidos de telemetria e os resultados produzidos
pelo algoritmo que define a pré-decolagem.


O algoritmo considera uma nave que pode decolar (resultado: PRONTA PARA DECOLAR), quando:

- temperatura interna entre 18 e 35 °C;
- temperatura externa entre -5 e 30 °C;
- integridade estrutural igual a 1;
- nível de energia igual ou superior a 60%;
- energia disponível não pode ser superior à energia máxima;
- pressão do tanque entre 95 e 145 bar;
- módulos críticos com status igual a 1.

Dessa forma quero que você realize uma análise complementar, composta por:
- Classificação dos dados;
- Análise das decisões;
- Sugestões de cuidado com o equipamento com base nas decisões e dados da telemetria

Não altere a decisão do algoritmo. Caso discorde de alguma
decisão, apenas sinalize a situação e explique o motivo.
Segue o dataset com os dados coletados da telemetria e as análises e decisão gerada pelo algoritmo {dados_para_ia}
""")

**Visualizando a resposta da IA**

In [15]:
print(resposta.text)

### **Relatório de Apoio à Análise Operacional de Pré-Decolagem**

**Sistema:** Operações de Voo e Análise de Telemetria
**Período de Análise:** 08/09/2026 — 12:00:00 às 19:15:00 (30 leituras telemétricas)

---

### **1. Classificação dos Dados**

A telemetria avaliada compreende 30 intervalos de amostragem (a cada 15 minutos). A classificação quantitativa e o estado das variáveis operacionais são apresentados abaixo:

#### **Status Global de Decolagem:**
* **PRONTO PARA DECOLAR:** 10 ocorrências (**33,3%** dos registros)
* **DECOLAGEM ABORTADA:** 20 ocorrências (**66,7%** dos registros)

#### **Distribuição dos Parâmetros Telemétricos:**

1. **Nível de Energia (Bateria/Gerador):**
   * **Limites esperados:** 60,0% a 100,0%
   * **Comportamento:** Foi a **principal causa de aborto**. Registrou pico mínimo de **13,75%** (13:45) e um pico anômalo máximo de **125,10%** (17:45). Esteve abaixo de 60% em 16 amostragens e acima de 100% em 1 amostragem.

2. **Pressão do Tanque:**
   * **Limites esperados:** 95,0 a 145,0 bar
   * **Comportamento:** Apresentou **alta volatilidade**. Valores mínimos atingiram **67,59 bar** (17:45) e **75,42 bar** (13:00). Valores máximos atingiram níveis críticos de **210,85 bar** (12:45) e **210,57 bar** (14:00). Fora dos limites em 5 amostragens.

3. **Temperatura Interna:**
   * **Limites esperados:** 18,0 °C a 35,0 °C
   * **Comportamento:** Manteve-se majoritariamente nominal (entre 18,20 °C e 34,75 °C), com exceção de um pico grave de **47,80 °C** registrado às 17:00.

4. **Temperatura Externa:**
   * **Limites esperados:** -5,0 °C a 30,0 °C
   * **Comportamento:** **100% Nominal.** Variou entre -2,24 °C (17:30) e 29,91 °C (15:15).

5. **Integridade Estrutural:**
   * **Limite esperado:** 1
   * **Comportamento:** **100% Nominal.** Manteve-se em 1 ao longo de todo o período.

6. **Status dos Módulos Críticos:**
   * **Limite esperado:** 1
   * **Comportamento:** Registrou falhas (`status = 0`) em duas ocasiões: às **17:00** e às **18:00**.

---

### **2. Análise das Decisões**

#### **Avaliação da Conformidade do Algoritmo:**
* **Resultado do Diagnóstico:** **Concordância de 100% com as regras do algoritmo.**
* Não foram identificados erros lógicos ou incoerências entre a telemetria fornecida e as decisões emitidas pelo algoritmo. Todas as 20 rejeições e 10 aprovações aplicaram estritamente as regras de corte definidas.

#### **Detalhamento dos Motivos de Interrupção (Decolagem Abortada):**
* **Nível de energia insuficiente (< 60%):** Presente em 16 das 20 decisões de aborto.
* **Pressão do tanque fora do limite:** Presente em 5 decisões de aborto (2 por sobrepressão grave >210 bar e 3 por subpressão <95 bar).
* **Módulo crítico com falha:** Presente em 2 decisões de aborto (17:00 e 18:00).
* **Energia acima da capacidade máxima (> 100%):** Presente em 1 decisão de aborto (17:45).
* **Temperatura interna fora do limite:** Presente em 1 decisão de aborto (17:00).

*Nota de Evento Múltiplo:* Algumas janelas apresentaram falhas combinadas, como às 12:45 (baixa energia + sobrepressão), 17:00 (superaquecimento interno + falha em módulo crítico) e 17:45 (sobrecarga de energia + subpressão).

---

### **3. Sugestões de Cuidado com o Equipamento**

Com base na dinâmica dos dados telemétricos, a equipe de engenharia e manutenção deve focar nas seguintes ações corretivas e preventivas:

#### **A. Sistema de Gerenciamento de Baterias (BMS) e Distribuição de Energia**
* **Calibração e Teste de Células:** O registro de **125,10%** de energia às 17:45 indica falha de calibração do sensor de estado de carga (SoC) ou falha no circuito de corte de carga (*overcharge*). Há risco iminente de dano térmico ou químico às baterias.
* **Investigação de Taxa de Descarga:** A queda brusca de 55,3% para 13,7% entre 13:30 e 13:45 indica fuga de corrente ou alta carga parasita no barramento elétrico.

#### **B. Válvulas de Alívio e Transdutores de Pressão do Tanque**
* **Inspeção de Válvulas de Sobrepressão:** O tanque atingiu pressões superiores a **210 bar** (duas vezes acima do limite seguro de 145 bar). Deve-se inspecionar as válvulas de alívio e checar se houve deformação plástica microestrutural na tubulação/tanque.
* **Verificação do Sistema de Injeção/Selagem:** As quedas abruptas de pressão (ex.: 67,59 bar às 17:45) sugerem vazamentos intermitentes nas linhas de pressurização ou travamento de válvulas solenoides.

#### **C. Sistema de Controle Climatológico (HVAC Interno) e Aviônicos**
* **Investigação de Estresse Térmico em Módulos Críticos:** O pico de **47,80 °C** às 17:00 coincidiu exatamente com a falha do módulo crítico (`status = 0`). Isso aponta que o módulo sofreu *thermal throttling* ou desligamento de proteção por superaquecimento. Recomenda-se realizar testes de estresse térmico na aviônica e inspecionar a bomba de fluido de arrefecimento da cabine.
* **Diagnóstico de Falhas Intermitentes:** O módulo crítico retornou ao status `1` nas leituras seguintes após falhar (17:00 e 18:00). Falhas intermitentes indicam mau contato em conectores, oxidação ou sensibilidade a picos de tensão.

---
**Conclusão Operacional:** A nave encontra-se em um ciclo de operação **instável**. Recomenda-se suspender as tentativas de lançamento até que os sistemas de **pressurização do combustível** e de **gerenciamento de energia (BMS)** passem por manutenção preventiva completa em solo.